project:
  type: website
  output-dir: docs
  resources:
    - styles.css
    - typing.js
    - \usepackage{pdfpages}


website:
  title: "Iris Chen"

  
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd #projects
      - text: "Posts"
        href: posts.qmd #news
      - text: "Photos"
        href: photos.qmd
    

format:
  html:
    theme: flatly
    css: styles.css

editor: visual

